# Generated by Django 4.2.19 on 2025-08-16 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndividualClient",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Middle Name",
                    ),
                ),
                ("birth_date", models.DateField(verbose_name="Birth Date")),
                ("address", models.TextField(verbose_name="Address")),
                (
                    "payment_method",
                    models.CharField(max_length=20, verbose_name="Payment Method"),
                ),
            ],
            options={
                "verbose_name": "Individual Client",
                "verbose_name_plural": "Individual Clients",
            },
            bases=("accounts.user",),
        ),
        migrations.CreateModel(
            name="LegalEntityClient",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=255, verbose_name="Company Name"),
                ),
                ("inn", models.CharField(max_length=12, verbose_name="INN")),
                ("kpp", models.CharField(max_length=9, verbose_name="KPP")),
                ("ogrn", models.CharField(max_length=15, verbose_name="OGRN")),
                ("legal_address", models.TextField(verbose_name="Legal Address")),
                ("actual_address", models.TextField(verbose_name="Actual Address")),
                (
                    "contact_person",
                    models.CharField(max_length=255, verbose_name="Contact Person"),
                ),
                ("position", models.CharField(max_length=255, verbose_name="Position")),
                ("bik", models.CharField(max_length=9, verbose_name="BIK")),
                (
                    "account_number",
                    models.CharField(max_length=20, verbose_name="Account Number"),
                ),
                (
                    "bank_name",
                    models.CharField(max_length=255, verbose_name="Bank Name"),
                ),
                (
                    "signature_type",
                    models.CharField(max_length=20, verbose_name="Signature Type"),
                ),
            ],
            options={
                "verbose_name": "Legal Entity",
                "verbose_name_plural": "Legal Entities",
            },
            bases=("accounts.user",),
        ),
    ]
