# Generated by Django 4.2.19 on 2025-08-25 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        # Удаляем старые таблицы, которые наследуются от User
        migrations.RunSQL(
            "DROP TABLE IF EXISTS clients_individualclient CASCADE;",
            reverse_sql="-- Cannot reverse this operation"
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS clients_legalentityclient CASCADE;",
            reverse_sql="-- Cannot reverse this operation"
        ),
        
        # Создаем новые таблицы с правильной структурой
        migrations.RunSQL(
            """
            CREATE TABLE clients_individualclient (
                id SERIAL PRIMARY KEY,
                user_id INTEGER UNIQUE REFERENCES accounts_user(id) ON DELETE CASCADE,
                middle_name VARCHAR(150),
                birth_date DATE,
                address TEXT,
                payment_method VARCHAR(20)
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS clients_individualclient;"
        ),
        
        migrations.RunSQL(
            """
            CREATE TABLE clients_legalentityclient (
                id SERIAL PRIMARY KEY,
                user_id INTEGER UNIQUE REFERENCES accounts_user(id) ON DELETE CASCADE,
                company_name VARCHAR(255) NOT NULL,
                inn VARCHAR(12) NOT NULL,
                kpp VARCHAR(9) NOT NULL,
                ogrn VARCHAR(15) NOT NULL,
                legal_address TEXT NOT NULL,
                actual_address TEXT,
                contact_person VARCHAR(255) NOT NULL,
                position VARCHAR(255) NOT NULL,
                bik VARCHAR(9) NOT NULL,
                account_number VARCHAR(20) NOT NULL,
                bank_name VARCHAR(255) NOT NULL,
                signature_type VARCHAR(20)
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS clients_legalentityclient;"
        ),
    ]
