# Generated by Django 4.2.19 on 2025-08-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0004_add_phone_column"),
    ]

    operations = [
        migrations.AddField(
            model_name="individualclient",
            name="phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="Phone"),
        ),
    ]
