# Generated by Django 4.2.19 on 2025-08-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0005_individualclient_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="individualclient",
            name="client_type",
            field=models.CharField(
                choices=[("customer", "Заказчик"), ("contractor", "Подрядчик")],
                default="customer",
                max_length=20,
                verbose_name="Client Type",
            ),
        ),
        migrations.AddField(
            model_name="legalentityclient",
            name="client_type",
            field=models.CharField(
                choices=[("customer", "Заказчик"), ("contractor", "Подрядчик")],
                default="customer",
                max_length=20,
                verbose_name="Client Type",
            ),
        ),
    ]
