# Generated by Django 4.2.19 on 2025-08-25 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("specialists", "0002_auto_20250825_2155"),
    ]

    operations = [
        # Делаем поле portfolio необязательным
        migrations.RunSQL(
            "ALTER TABLE specialists_specialistprofile ALTER COLUMN portfolio DROP NOT NULL;",
            reverse_sql="ALTER TABLE specialists_specialistprofile ALTER COLUMN portfolio SET NOT NULL;"
        ),
    ]
