# Generated by Django 4.2.19 on 2025-08-25 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("specialists", "0003_auto_20250825_2239"),
    ]

    operations = [
        # Проверяем и исправляем структуру таблицы specialists_specialistprofile
        migrations.RunSQL(
            """
            -- Убеждаемся, что все поля существуют и имеют правильные типы
            DO $$
            BEGIN
                -- Проверяем, существует ли поле portfolio
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name = 'specialists_specialistprofile' 
                    AND column_name = 'portfolio'
                ) THEN
                    ALTER TABLE specialists_specialistprofile ADD COLUMN portfolio VARCHAR(200);
                END IF;
                
                -- Проверяем, существует ли поле certificates
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name = 'specialists_specialistprofile' 
                    AND column_name = 'certificates'
                ) THEN
                    ALTER TABLE specialists_specialistprofile ADD COLUMN certificates TEXT;
                END IF;
                
                -- Убеждаемся, что поле portfolio может принимать NULL
                ALTER TABLE specialists_specialistprofile ALTER COLUMN portfolio DROP NOT NULL;
                
                -- Убеждаемся, что поле certificates может принимать NULL
                ALTER TABLE specialists_specialistprofile ALTER COLUMN certificates DROP NOT NULL;
            END $$;
            """,
            reverse_sql="-- Cannot reverse this operation"
        ),
    ]
