# Generated by Django 4.2.19 on 2025-08-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specialists", "0004_auto_20250825_2255"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="specialistprofile",
            name="bio",
        ),
        migrations.AddField(
            model_name="specialistprofile",
            name="about",
            field=models.TextField(blank=True, help_text="О себе"),
        ),
        migrations.AlterField(
            model_name="specialistprofile",
            name="availability",
            field=models.CharField(
                blank=True, help_text="Доступность", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="specialistprofile",
            name="certificates",
            field=models.TextField(blank=True, help_text="Сертификаты"),
        ),
        migrations.AlterField(
            model_name="specialistprofile",
            name="experience",
            field=models.CharField(blank=True, help_text="Опыт работы", max_length=100),
        ),
        migrations.AlterField(
            model_name="specialistprofile",
            name="hourly_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Почасовая ставка",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="specialistprofile",
            name="portfolio",
            field=models.URLField(
                blank=True, help_text="Ссылка на портфолио", null=True
            ),
        ),
        migrations.AlterField(
            model_name="specialistprofile",
            name="specialization",
            field=models.CharField(
                blank=True, help_text="Специализации через запятую", max_length=500
            ),
        ),
    ]
