# Generated by Django 4.2.19 on 2025-08-26 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "specialists",
            "0005_remove_specialistprofile_bio_specialistprofile_about_and_more",
        ),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE specialists_specialistprofile ALTER COLUMN availability DROP NOT NULL;',
            reverse_sql='ALTER TABLE specialists_specialistprofile ALTER COLUMN availability SET NOT NULL;'
        ),
    ]
