# Generated by Django 4.2.19 on 2025-08-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specialists", "0006_fix_availability_null_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialistprofile",
            name="specialist_type",
            field=models.CharField(
                choices=[("executor", "Исполнитель"), ("manager", "BIM-менеджер")],
                default="executor",
                max_length=20,
            ),
        ),
    ]
