# Generated by Django 4.2.19 on 2025-08-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("news", "Новости"),
                    ("tips", "Советы"),
                    ("technology", "Технологии"),
                    ("training", "Обучение"),
                ],
                default="news",
                max_length=20,
                verbose_name="Категория",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="preview",
            field=models.TextField(blank=True, max_length=500, verbose_name="Превью"),
        ),
    ]
