# Generated by Django 4.2.19 on 2025-08-26 16:45:00

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchitecturalProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('description', models.TextField(default='', verbose_name='Описание')),
                ('functional_class', models.CharField(blank=True, max_length=100, null=True, verbose_name='Функциональный класс')),
                ('construction_system', models.CharField(blank=True, max_length=255, null=True, verbose_name='Конструктивная система')),
                ('total_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Общая площадь')),
                ('building_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Объем здания')),
                ('footprint_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Площадь застройки')),
                ('documentation', models.TextField(default='', verbose_name='Документация')),
                ('design_duration', models.IntegerField(default=0, verbose_name='Длительность проектирования')),
                ('design_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость проектирования')),
                ('image_main', models.CharField(blank=True, max_length=255, null=True, verbose_name='Главное изображение')),
                ('image_plan', models.CharField(blank=True, max_length=255, null=True, verbose_name='План')),
                ('image_interior1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Интерьер 1')),
                ('image_interior2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Интерьер 2')),
                ('user_comments', models.IntegerField(default=0, verbose_name='Комментарии')),
                ('downloads', models.IntegerField(default=0, verbose_name='Загрузки')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('rating_average', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Средний рейтинг')),
                ('rating_count', models.PositiveIntegerField(default=0, verbose_name='Количество оценок')),
            ],
            options={
                'verbose_name': 'Архитектурный проект',
                'verbose_name_plural': 'Архитектурные проекты',
                'db_table': 'architectural_projects',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Оценка от 1 до 5 звезд', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оценки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='architectural_projects.architecturalproject', verbose_name='Проект')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оценка проекта',
                'verbose_name_plural': 'Оценки проектов',
                'ordering': ['-created_at'],
                'unique_together': {('project', 'user')},
            },
        ),
    ]
