# Generated by Django 4.2.19 on 2025-08-28 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("architectural_projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP адрес"
                    ),
                ),
                (
                    "viewed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата просмотра"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_views",
                        to="architectural_projects.architecturalproject",
                        verbose_name="Проект",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Просмотр проекта",
                "verbose_name_plural": "Просмотры проектов",
                "ordering": ["-viewed_at"],
                "unique_together": {("project", "ip_address"), ("project", "user")},
            },
        ),
    ]
