# Generated by Django 4.2.19 on 2025-08-29 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("architectural_projects", "0002_projectview"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectview",
            options={
                "ordering": ["-viewed_at"],
                "verbose_name": "Просмотр архитектурного проекта",
                "verbose_name_plural": "Просмотры архитектурных проектов",
            },
        ),
        migrations.AlterField(
            model_name="projectview",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="IP-адрес"
            ),
        ),
        migrations.AlterField(
            model_name="projectview",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="architectural_project_views",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
