# Generated by Django 4.2.19 on 2025-08-30 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("architectural_projects", "0002_increase_design_cost_1000x"),
        ("architectural_projects", "0003_alter_projectview_options_and_more"),
    ]

    operations = []
