# Generated by Django 4.2.19 on 2025-08-16 11:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("in_progress", "В работе"),
                            ("completed", "Завершен"),
                            ("archived", "В архиве"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("architectural", "Архитектурная часть"),
                            ("structural", "Конструктивная часть"),
                            ("engineering", "Инженерная часть"),
                            ("general", "Общая часть"),
                        ],
                        max_length=20,
                        verbose_name="Тип раздела",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Последнее обновление"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Раздел проекта",
                "verbose_name_plural": "Разделы проекта",
                "unique_together": {("project", "section_type")},
            },
        ),
        migrations.CreateModel(
            name="ProjectSectionFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=projects.models.project_section_file_path,
                        verbose_name="Файл",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "file_type",
                    models.CharField(max_length=10, verbose_name="Тип файла"),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=projects.models.project_section_file_path,
                        verbose_name="Миниатюра",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата загрузки"
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="projects.projectsection",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_section_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Файл раздела",
                "verbose_name_plural": "Файлы разделов",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("bim_manager", "BIM-менеджер"),
                            ("architect", "Архитектор"),
                            ("constructor", "Конструктор"),
                            ("engineer", "Инженер"),
                            ("viewer", "Просмотр"),
                        ],
                        max_length=20,
                        verbose_name="Роль",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата назначения"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Роль в проекте",
                "verbose_name_plural": "Роли в проекте",
                "unique_together": {("project", "user")},
            },
        ),
        migrations.CreateModel(
            name="ProjectComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Комментарий")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Добавлен"),
                ),
                (
                    "image_coordinates",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Координаты на изображении"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="projects.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="team_members",
            field=models.ManyToManyField(
                related_name="project_memberships",
                through="projects.ProjectRole",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Участники проекта",
            ),
        ),
        migrations.CreateModel(
            name="ArchitecturalProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Наименование")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, unique=True, verbose_name="URL"
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        choices=[
                            ("residential", "Жилой"),
                            ("commercial", "Коммерческий"),
                            ("industrial", "Промышленный"),
                            ("public", "Общественный"),
                            ("mixed", "Смешанный"),
                        ],
                        max_length=20,
                        verbose_name="Тип объекта",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("in_progress", "В разработке"),
                            ("completed", "Завершен"),
                            ("archived", "В архиве"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "total_area",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Общая площадь (м²)",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Стоимость (₽)",
                    ),
                ),
                (
                    "price_per_meter",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Стоимость за м² (₽)",
                    ),
                ),
                (
                    "view_3d",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=projects.models.architectural_project_image_path,
                        verbose_name="3D вид",
                    ),
                ),
                (
                    "floor_plans",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=projects.models.architectural_project_image_path,
                        verbose_name="Планы этажей",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество просмотров"
                    ),
                ),
                (
                    "comments_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество комментариев"
                    ),
                ),
                (
                    "likes_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество лайков"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="architectural_projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Проект в каталоге",
                "verbose_name_plural": "Каталог проектов",
                "ordering": ["-created_at"],
            },
        ),
    ]
