# Generated by Django 4.2.19 on 2025-08-29 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="air_conditioning",
            field=models.TextField(
                blank=True, verbose_name="Система кондиционирования"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="architectural_concept",
            field=models.TextField(blank=True, verbose_name="Архитектурная концепция"),
        ),
        migrations.AddField(
            model_name="project",
            name="automation_systems",
            field=models.TextField(blank=True, verbose_name="Системы автоматизации"),
        ),
        migrations.AddField(
            model_name="project",
            name="backup_power",
            field=models.TextField(
                blank=True, verbose_name="Резервное электроснабжение"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="building_area",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Площадь застройки (м²)",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="cold_water_system",
            field=models.TextField(blank=True, verbose_name="Система холодоснабжения"),
        ),
        migrations.AddField(
            model_name="project",
            name="communication_networks",
            field=models.TextField(blank=True, verbose_name="Сети связи"),
        ),
        migrations.AddField(
            model_name="project",
            name="construction_queue",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Очередь строительства"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="construction_volume",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Строительный объем (м³)",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="design_stage",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Стадия проектирования"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="electrical_load",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Электрическая нагрузка (кВт)",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="electrical_system",
            field=models.TextField(blank=True, verbose_name="Система электроснабжения"),
        ),
        migrations.AddField(
            model_name="project",
            name="energy_efficiency",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Класс энергоэффективности"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="environmental_impact",
            field=models.TextField(
                blank=True, verbose_name="Воздействие на окружающую среду"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="evacuation_routes",
            field=models.TextField(blank=True, verbose_name="Пути эвакуации"),
        ),
        migrations.AddField(
            model_name="project",
            name="facade_materials",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Материалы фасадов"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="fire_extinguishing",
            field=models.TextField(blank=True, verbose_name="Системы пожаротушения"),
        ),
        migrations.AddField(
            model_name="project",
            name="fire_safety",
            field=models.TextField(blank=True, verbose_name="Пожарная безопасность"),
        ),
        migrations.AddField(
            model_name="project",
            name="floors",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Этажность"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="foundation_type",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Тип фундамента"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="grounding_system",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Система заземления"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="heating_load",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Тепловая нагрузка (кВт)",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="heating_system",
            field=models.TextField(blank=True, verbose_name="Система отопления"),
        ),
        migrations.AddField(
            model_name="project",
            name="interior_finish",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Отделка интерьеров"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="it_infrastructure",
            field=models.TextField(blank=True, verbose_name="IT-инфраструктура"),
        ),
        migrations.AddField(
            model_name="project",
            name="landscape_design",
            field=models.TextField(
                blank=True, verbose_name="Ландшафтное проектирование"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="launch_complexes",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Пусковые комплексы"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="object_code",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Шифр объекта"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="roof_type",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Тип кровли"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="security_systems",
            field=models.TextField(blank=True, verbose_name="Системы безопасности"),
        ),
        migrations.AddField(
            model_name="project",
            name="seismic_resistance",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Сейсмостойкость"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="sewerage_system",
            field=models.TextField(blank=True, verbose_name="Система канализации"),
        ),
        migrations.AddField(
            model_name="project",
            name="structural_system",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Конструктивная система"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="sustainability_features",
            field=models.TextField(
                blank=True, verbose_name="Экологические особенности"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="total_area",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Общая площадь (м²)",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="ventilation_system",
            field=models.TextField(blank=True, verbose_name="Система вентиляции"),
        ),
        migrations.AddField(
            model_name="project",
            name="wall_materials",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Материалы стен"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="water_consumption",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Расход воды (л/с)",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="water_supply_system",
            field=models.TextField(
                blank=True, verbose_name="Система внутреннего и наружного водоснабжения"
            ),
        ),
        migrations.CreateModel(
            name="ProjectView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP адрес"
                    ),
                ),
                (
                    "viewed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата просмотра"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_views",
                        to="projects.project",
                        verbose_name="Проект",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_views",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Просмотр проекта",
                "verbose_name_plural": "Просмотры проектов",
                "ordering": ["-viewed_at"],
                "unique_together": {("project", "user"), ("project", "ip_address")},
            },
        ),
    ]
