# Generated by Django 4.2.19 on 2025-08-29 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_bimfamilycategory_remove_order_budget_and_more"),
    ]

    operations = [
        # Все поля уже удалены или не существуют
    ]
