# Generated by Django 4.2.19 on 2025-08-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_cleanup_order_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="comment_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата комментария"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="customer_comment",
            field=models.TextField(blank=True, verbose_name="Комментарий заказчика"),
        ),
    ]
