# Generated by Django 4.2.19 on 2025-08-30 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0006_add_customer_comment_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderpayment",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="orderpayment",
            old_name="payment_date",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="orderpayment",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderpayment",
            name="payment_method",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="orderpayment",
            name="payment_type",
            field=models.CharField(
                choices=[("advance", "Аванс"), ("final", "Финальный платеж")],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="OrderFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="order_files/%Y/%m/%d/", verbose_name="Файл"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название файла"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата загрузки"
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("sketch", "Эскиз"),
                            ("draft", "Чертеж"),
                            ("final", "Финальный файл"),
                            ("other", "Другое"),
                        ],
                        default="other",
                        max_length=50,
                        verbose_name="Тип файла",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="orders.order",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_files",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Загрузил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Файл заказа",
                "verbose_name_plural": "Файлы заказов",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
