# Generated by Django 4.2.19 on 2025-09-13 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0007_alter_orderpayment_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="calculated_budget",
        ),
        migrations.RemoveField(
            model_name="order",
            name="percentage_change",
        ),
        migrations.RemoveField(
            model_name="order",
            name="reference_project",
        ),
        migrations.CreateModel(
            name="OrderFileComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="Текст комментария")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="orders.orderfile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий к файлу",
                "verbose_name_plural": "Комментарии к файлам",
                "ordering": ["-created_at"],
            },
        ),
    ]
