# Generated by Django 4.2.19 on 2025-08-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_role",
            field=models.CharField(
                blank=True,
                choices=[("customer", "Заказчик"), ("contractor", "Подрядчик")],
                default="customer",
                max_length=20,
                null=True,
            ),
        ),
    ]
