# Generated by Django 4.2.19 on 2025-09-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_role",
            field=models.CharField(
                blank=True,
                choices=[("customer", "Заказчик"), ("contractor", "Подрядчик")],
                default="customer",
                max_length=20,
                null=True,
                verbose_name="Тип специалиста",
            ),
        ),
    ]
