# Generated by Django 5.1.6 on 2024-01-01 00:00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BimFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('technical_specs', models.JSONField(default=dict)),
                ('basic_specs', models.JSONField(default=dict)),
                ('catalog_items', models.JSONField(default=list)),
                ('company_info', models.JSONField(default=dict)),
                ('download_info', models.JSONField(default=dict)),
                ('parsing_method', models.CharField(max_length=50)),
                ('total_images', models.IntegerField(default=0)),
                ('parsed_at', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'BIM Семейство',
                'verbose_name_plural': 'BIM Семейства',
                'db_table': 'families_bimfamily_2',
            },
        ),
        migrations.CreateModel(
            name='FamilyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_path', models.TextField()),
                ('alt_text', models.TextField(blank=True)),
                ('title', models.TextField(blank=True)),
                ('image_type', models.CharField(blank=True, max_length=50)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('local_filename', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bim_families.bimfamily')),
            ],
            options={
                'verbose_name': 'Изображение семейства',
                'verbose_name_plural': 'Изображения семейств',
                'db_table': 'family_images_2',
            },
        ),
    ]
