# Generated by Django 4.2.19 on 2025-08-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bim_families", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bimfamily",
            name="comments",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="bimfamily",
            name="downloads",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="bimfamily",
            name="rating",
            field=models.DecimalField(decimal_places=1, default=4.5, max_digits=3),
        ),
        migrations.AddField(
            model_name="bimfamily",
            name="views",
            field=models.IntegerField(default=0),
        ),
    ]
