# Generated by Django 4.2.19 on 2025-08-28 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bim_families", "0002_bimfamily_comments_bimfamily_downloads_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="familyimage",
            name="alt_text",
        ),
        migrations.RemoveField(
            model_name="familyimage",
            name="file_size",
        ),
        migrations.RemoveField(
            model_name="familyimage",
            name="height",
        ),
        migrations.RemoveField(
            model_name="familyimage",
            name="local_filename",
        ),
        migrations.RemoveField(
            model_name="familyimage",
            name="title",
        ),
        migrations.RemoveField(
            model_name="familyimage",
            name="width",
        ),
        migrations.AlterField(
            model_name="familyimage",
            name="image_type",
            field=models.CharField(default="preview", max_length=50),
        ),
        migrations.AlterField(
            model_name="familyimage",
            name="local_path",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterModelTable(
            name="familyimage",
            table="families_familyimage_2",
        ),
        migrations.CreateModel(
            name="FamilyView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP адрес"
                    ),
                ),
                (
                    "viewed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата просмотра"
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_views",
                        to="bim_families.bimfamily",
                        verbose_name="BIM Семейство",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Просмотр семейства",
                "verbose_name_plural": "Просмотры семейств",
                "ordering": ["-viewed_at"],
                "unique_together": {("family", "user"), ("family", "ip_address")},
            },
        ),
    ]
