# Generated by Django 4.2.19 on 2025-08-29 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bim_families", "0004_alter_familyview_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bimfamily",
            old_name="comments",
            new_name="downloads_count",
        ),
        migrations.RenameField(
            model_name="bimfamily",
            old_name="downloads",
            new_name="views_count",
        ),
        migrations.RenameField(
            model_name="familyimage",
            old_name="created_at",
            new_name="uploaded_at",
        ),
        migrations.RemoveField(
            model_name="bimfamily",
            name="basic_specs",
        ),
        migrations.RemoveField(
            model_name="bimfamily",
            name="catalog_items",
        ),
        migrations.RemoveField(
            model_name="bimfamily",
            name="company_info",
        ),
        migrations.RemoveField(
            model_name="bimfamily",
            name="download_info",
        ),
        migrations.RemoveField(
            model_name="bimfamily",
            name="external_id",
        ),
        migrations.RemoveField(
            model_name="bimfamily",
            name="parsed_at",
        ),
        migrations.RemoveField(
            model_name="bimfamily",
            name="parsing_method",
        ),
        migrations.RemoveField(
            model_name="bimfamily",
            name="technical_specs",
        ),
        migrations.RemoveField(
            model_name="bimfamily",
            name="total_images",
        ),
        migrations.RemoveField(
            model_name="bimfamily",
            name="url",
        ),
        migrations.RemoveField(
            model_name="bimfamily",
            name="views",
        ),
        migrations.RemoveField(
            model_name="familyimage",
            name="image_type",
        ),
        migrations.RemoveField(
            model_name="familyimage",
            name="local_path",
        ),
    ]
