# Generated by Django 4.2.19 on 2025-08-29 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bim_families", "0005_rename_comments_bimfamily_downloads_count_and_more"),
    ]

    operations = [

        migrations.AddField(
            model_name="bimfamily",
            name="cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="bimfamily",
            name="family_type",
            field=models.CharField(default="Не указан", max_length=100),
        ),
        migrations.AddField(
            model_name="bimfamily",
            name="manufacturer",
            field=models.CharField(default="Не указан", max_length=200),
        ),
        migrations.AddField(
            model_name="bimfamily",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="familyimage",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="bim_families/"),
        ),
        migrations.AlterField(
            model_name="bimfamily",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="bimfamily",
            name="rating",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
