# Generated by Django 4.2.19 on 2025-08-29 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_add_category_field"),
        ("bim_families", "0006_bimfamily_category_bimfamily_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bimfamily",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="orders.bimfamilycategory",
            ),
        ),
    ]
